services:
    _defaults:
        public: true

    cartest.repository:
        class: PrestaShop\Module\Car\Entity\Repository\CarTestRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PrestaShop\Module\Car\Entity\CarTest
