ccc:
    path: /test
    methods: [GET, POST]
    controller: PrestaShop\Module\Car\Controller\DemoController::demoAction

    # defaults:
    #   _controller: Modules\Car\Controller:DemoController::demoAction
