<?php

namespace PrestaShop\Module\Car\Repository;

/**
 * AttributeGroupLangRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarTestRepository extends \Doctrine\ORM\EntityRepository
{
    // public function
}
