services:
    _defaults:
      public: true

    texttranslate.service:
        class: PrestaShop\Module\TextTranslate\Service\TranslateService
        arguments:
          - '@doctrine.orm.default_entity_manager'
          - '@prestashop.core.admin.tablang.repo'
          - '@prestashop.core.admin.translation.repo'
          - '@prestashop.core.admin.translation.repository'
          - '@prestashop.core.admin.tablang.repository'
          - '@prestashop.core.admin.lang.repository'
          
    prestashop.core.admin.tablang.repo:
        class: PrestaShop\Module\TextTranslate\Repository\TabLangRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PrestaShop\Module\TextTranslate\Entity\TabLang
          
    prestashop.core.admin.translation.repo:
        class: PrestaShop\Module\TextTranslate\Repository\TranslationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PrestaShop\Module\TextTranslate\Entity\Translation

    prestashop.core.admin.tablang.repository:
        class: PrestaShopBundle\Entity\Repository\TabLangRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PrestaShopBundle\Entity\TabLang
